[package]
name = "bottom-line"
version = "0.1.0"
edition = "2024"

[dependencies]
either = { version = "1.15.0", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
